config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: 'show'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @new_task = Task.new
  end

  def create
    @create_task = Task.new(task_params)
    @create_task.save
    redirect_to show_path(@create_task)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @edit_task = Task.find(params[:id])
  end

  def update
    @update_task = Task.find(params[:id])
    @update_task.update(task_params)
    redirect_to show_path(@update_task)
  end

  def destroy
    @destroy_task = Task.find(params[:id])
    @destroy_task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<br>
<h2>Edit task</h2>

<%= form_for(@edit_task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<br>
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, show_path(task.id) %></li>
  <% end %>
</ul>

<%= link_to "Create a new task", tasks_new_path%>

app/views/tasks/new.html.erb
<br>
<h2>New task</h2>
<%= form_for(@new_task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

<br>
<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<br>
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p>
<% if @task.completed %>
  <%= "This task is completed" %>
<% else %>
  <%= "This task is not completed yet" %>
<% end %>
<br>
<br>


<%= link_to 'Back to list', tasks_path %>